### ISSUE TITLE
Incorrect function

### ISSUE THREAD

**Issue by CryptoKiddies** [bokkypoobah/Tokens#2]
https://github.com/bokkypoobah/Tokens/blob/efcbb37e0de99f05d7eac2170b8aed420273070d/contracts/FixedSupplyToken.sol#L221

This function is incorrect. The transfer method atteched to contract will send ether from message contract to owner, not token.

Replace with this:

```
function transferAnyERC20Token(uint tokens) public onlyOwner returns (bool success) {
        require(tokens <= balances[address(this)]);
        balances[address(this)] = balances[address(this)].sub(tokens);
        balances[msg.sender] = balances[msg.sender].add(tokens);
        emit Transfer(address(this), msg.sender, tokens);
        return true;
    }
```

**Comment by pukimusedap** [comment]
function transferAnyERC20Token(uint tokens) public onlyOwner returns (bool success) {
        require(tokens <= balances[address(this)]);
        balances[address(this)] = balances[address(this)].sub(tokens);
        balances[msg.sender] = balances[msg.sender].add(tokens);
        emit Transfer(address(this), msg.sender, tokens);
        return true;
    }

**Comment by CryptoKiddies** [comment]
sorry about the cryptopunk:/
